# -*- coding: utf-8 -*-
"""EDA_and_anomaly_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SCnFf041k7F3NAOfxoq8DoC6hbF_nPc4

#Data Loading
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Reading Data
url = "https://raw.githubusercontent.com/yousefahmed06/Weather-Project/main/weather_data_features.csv"
df = pd.read_csv(url)

# #Date handling
# if 'dt_txt' in df.columns:
#     df['datetime'] = pd.to_datetime(df['dt_txt'])
#     df.set_index('datetime', inplace=True)

print("Data loading Successfully, Rows number: ", len(df))

"""#Statistical Analysis"""

stats_summary = df.describe().T
stats_summary['skewness'] = df.skew(numeric_only=True)

print(stats_summary[['mean', 'std', 'min', '50%', 'max', 'skewness']])

"""#Correlation Analysis"""

plt.figure(figsize=(16, 10))
sns.heatmap(df.corr(numeric_only=True), annot=True, fmt=".2f", cmap='coolwarm')
plt.title("Correlation Between Weather Features")
plt.show()

correlation = df.corr(numeric_only=True)['temp_c'].sort_values(ascending=False)
print("Correlation With Tempreture:\n", correlation)

"""#Time Series Analysis"""

#Graphing temperature change over time with a moving average
plt.figure(figsize=(12, 5))
plt.plot(df.index, df['temp_c'], label='Actual Temp', alpha=0.5)
plt.plot(df.index, df['temp_c'].rolling(window=8).mean(), label='24H Rolling Mean', color='red', linewidth=2)

plt.title("Temperature Trend Over Time")
plt.xlabel("Date/Time")
plt.ylabel("Temperature (°C)")
plt.legend()
plt.show()

"""#Anomaly Detection"""

#Explorin ouliers for wind speed
df['wind_zscore'] = (df['wind_speed'] - df['wind_speed'].mean()) / df['wind_speed'].std()

anomalies = df[np.abs(df['wind_zscore']) > 2.5]

print(f"An outlier has been found: {len(anomalies)} :")
print(anomalies[['temp_c', 'humidity', 'wind_speed']])

"""**Insights Extraction & Team Recommendations**
1. Key Exploratory & Statistical Findings

  Temperature & Humidity: The average temperature is 24.3°C (ranging between 4.8°C and 43.7°C), with an average humidity level of 53.8%.

  Data Distribution: Most weather variables follow a nearly normal distribution, though wind speeds and rainfall show positive skewness due to sudden weather spikes.

2. Correlation Highlights

  Strong Positive Correlation: High correlation observed between actual temperature (temp_c) and perceived temperature (feels_like_c).

  Inverse Relationships: A notable inverse correlation exists between atmospheric pressure (pressure) and temperature/humidity levels, where sudden drops in pressure frequently precede weather changes.

3. Anomaly Detection Results

  Wind Spikes: Detected multiple wind speed anomalies exceeding 9.3 m/s ($Z\text{-score} > 2.5$), indicating short-term severe weather events or gusts (wind_gust).

  Constant Attributes: Columns such as visibility and snow_3h_mm showed zero variance across the dataset and can be safely dropped during modeling.

4. Actionable Recommendations for Modeling

  Feature Selection: Exclude redundant features like visibility and snow_3h_mm to reduce noise.

  Lag Features: Introduce 3-hour and 6-hour lag features for pressure, humidity, and clouds_pct, as pressure drops provide strong predictive signals for temperature and precipitation shifts.
"""